'use strict';
const express=require('express'); const {requireRole}=require('../auth/middleware'); const {hashPassword,generateInitialPassword}=require('../auth/auth');
function adminRoutes({db,triggerRefresh}){const r=express.Router(); const log=(e,a,d)=>db.prepare('INSERT INTO activity_logs (user_email,action,detail) VALUES (?,?,?)').run(e,a,d||null);
 r.get('/users',requireRole('admin'),(q,s)=>s.json({users:db.prepare('SELECT id,email,name,role,assigned_agent,status,first_login_at,last_login_at,last_activity_at,created_at FROM users ORDER BY created_at DESC').all()}));
 r.post('/users',requireRole('admin'),(q,s)=>{const {email,name,role,assignedAgent}=q.body||{};if(!email||!['admin','manager','agent'].includes(role))return s.status(400).json({error:'INVALID_FIELDS'});if(role==='agent'&&!assignedAgent)return s.status(400).json({error:'MISSING_AGENT_MAPPING'});const p=generateInitialPassword();try{db.prepare('INSERT INTO users(email,name,password_hash,role,assigned_agent,must_change_password) VALUES(?,?,?,?,?,1)').run(email.toLowerCase(),name||null,hashPassword(p),role,assignedAgent||null);log(q.user.email,'Admin created user',email.toLowerCase());s.json({ok:true,initialPassword:p});}catch(e){s.status(409).json({error:'EMAIL_EXISTS'});}});
 r.patch('/users/:email',requireRole('admin'),(q,s)=>{const {role,assignedAgent,status,name}=q.body||{};if(role&&!['admin','manager','agent'].includes(role))return s.status(400).json({error:'INVALID_ROLE'});const fields=[],vals=[];for(const [k,col] of [['role','role'],['assignedAgent','assigned_agent'],['status','status'],['name','name']])if(q.body[k]!==undefined){fields.push(col+'=?');vals.push(q.body[k]);}if(!fields.length)return s.status(400).json({error:'NOTHING_TO_UPDATE'});vals.push(q.params.email.toLowerCase());db.prepare(`UPDATE users SET ${fields.join(',')} WHERE email=?`).run(...vals);log(q.user.email,'Admin updated user',q.params.email);s.json({ok:true});});
 r.post('/users/:email/reset-password',requireRole('admin'),(q,s)=>{const p=generateInitialPassword();db.prepare('UPDATE users SET password_hash=?,must_change_password=1 WHERE email=?').run(hashPassword(p),q.params.email.toLowerCase());db.prepare('UPDATE sessions SET revoked=1 WHERE user_id=(SELECT id FROM users WHERE email=?)').run(q.params.email.toLowerCase());s.json({ok:true,newPassword:p});});
 r.get('/logs/login',requireRole('admin'),(q,s)=>s.json({logs:db.prepare('SELECT * FROM login_logs ORDER BY login_at DESC LIMIT 300').all()}));
 r.get('/logs/activity',requireRole('admin'),(q,s)=>s.json({logs:db.prepare('SELECT * FROM activity_logs ORDER BY created_at DESC LIMIT 300').all()}));
 r.get('/logs/refresh',requireRole('admin','manager'),(q,s)=>s.json({logs:db.prepare('SELECT * FROM refresh_logs ORDER BY started_at DESC LIMIT 100').all()}));
 r.get('/kpi-config',requireRole('admin','manager'),(q,s)=>s.json({config:db.prepare('SELECT * FROM kpi_config ORDER BY city,provider,kpi,effective_from DESC').all()}));
 r.post('/kpi-config',requireRole('admin'),(q,s)=>{const b=q.body||{};if(!b.city||!b.provider||!b.kpi||b.bonusAmount==null||!b.effectiveFrom)return s.status(400).json({error:'MISSING_FIELDS'});db.prepare(`INSERT INTO kpi_config(city,provider,kpi,target,lower_boundary_pct,upper_boundary_pct,bonus_amount,effective_from,effective_to,active) VALUES(?,?,?,?,?,?,?,?,?,1)`).run(b.city,b.provider,b.kpi,b.target??null,b.lowerBoundaryPct??null,b.upperBoundaryPct??null,b.bonusAmount,b.effectiveFrom,b.effectiveTo??null);log(q.user.email,'Admin changed KPI config',`${b.city}/${b.provider}/${b.kpi}`);s.json({ok:true});});
 r.post('/refresh',requireRole('admin','manager'),async(q,s)=>{try{const x=await triggerRefresh(q.user.email);log(q.user.email,'Manual refresh',JSON.stringify(x));s.json(x);}catch(e){s.status(500).json({error:'REFRESH_FAILED',message:e.message});}});
 return r;}
module.exports=adminRoutes;
