'use strict';
const express=require('express'); const {requireAuth,scopeToOwnAgent}=require('../auth/middleware'); const {evaluateKPI}=require('../calculations/bonusEngine');
function dashboardRoutes({db,cacheStore}){
 const router=express.Router(); router.use(requireAuth);
 function filtered(req){let vs=[...(cacheStore.get()?.vendors||[])]; if(req.user.role==='agent')vs=vs.filter(v=>v.agent===req.user.assignedAgent); else if(req.query.agent)vs=vs.filter(v=>v.agent===req.query.agent); for(const k of ['city','provider','status'])if(req.query[k])vs=vs.filter(v=>String(v[k]||'')===String(req.query[k])); if(req.query.vendor)vs=vs.filter(v=>String(v.vendorId)===String(req.query.vendor)); return vs;}
 router.get('/meta',(req,res)=>{const s=cacheStore.get();res.json({lastUpdated:s?.builtAt||null,dataSourceHealthy:!!s,dataQuality:s?.dataQuality||null});});
 router.get('/filters',scopeToOwnAgent,(req,res)=>{const vs=filtered(req);res.json({cities:[...new Set(vs.map(v=>v.city).filter(Boolean))].sort(),providers:[...new Set(vs.map(v=>v.provider).filter(Boolean))].sort(),agents:[...new Set(vs.map(v=>v.agent).filter(Boolean))].sort(),vendors:vs.slice(0,5000).map(v=>({id:v.vendorId,name:v.vendorName,agent:v.agent,city:v.city,provider:v.provider})),statuses:[...new Set(vs.map(v=>v.status).filter(Boolean))].sort()});});
 router.get('/overview',scopeToOwnAgent,(req,res)=>{const s=cacheStore.get(); if(!s)return res.status(503).json({error:'NO_DATA',message:'No successful data refresh has completed yet.'}); const vs=filtered(req); const avg=(key)=>{const a=vs.map(v=>v[key]).filter(x=>typeof x==='number');return a.length?a.reduce((x,y)=>x+y,0)/a.length:null}; const sums=(key)=>vs.map(v=>v[key]).filter(x=>typeof x==='number').reduce((x,y)=>x+y,0); res.json({lastUpdated:s.builtAt,vendorCount:vs.length,kpis:{nfc:avg('nfcPct'),cancel:avg('cancelledPct'),return:avg('returnedPct'),refund:avg('refundPct'),availability:avg('availabilityPct'),hyperDelay:avg('delayPct'),assortment:avg('assortment'),acquisition:sums('acquisition')},vendors:vs.slice(0,500),dataQuality:s.dataQuality});});
 router.get('/vendors/:vendorId',scopeToOwnAgent,(req,res)=>{const v=filtered(req).find(x=>String(x.vendorId)===String(req.params.vendorId)); if(!v)return res.status(404).json({error:'NOT_FOUND'});res.json({vendor:v});});
 router.get('/map',scopeToOwnAgent,(req,res)=>res.json({markers:filtered(req).filter(v=>Number.isFinite(v.latitude)&&Number.isFinite(v.longitude)).map(v=>({id:v.vendorId,name:v.vendorName,agent:v.agent,city:v.city,provider:v.provider,status:v.status,liveDate:v.liveDate,churnDate:v.churnDate,lat:v.latitude,lng:v.longitude}))}));
 router.get('/table',scopeToOwnAgent,(req,res)=>{const vs=filtered(req);const page=Math.max(1,parseInt(req.query.page||'1'));const size=Math.min(100,Math.max(10,parseInt(req.query.pageSize||'50')));res.json({page,pageSize:size,total:vs.length,rows:vs.slice((page-1)*size,page*size)});});
 return router;
}
module.exports=dashboardRoutes;
