const $=s=>document.querySelector(s); const api=async(u,o={})=>{const r=await fetch('/api'+u,{credentials:'include',...o}); if(r.status===401){location.href='login.html';return null;} const d=await r.json(); if(!r.ok) throw new Error(d.message||d.error||'Request failed'); return d;};
let me=null, filters={}; const pages=['Overview','Vendor Performance','Agent Performance','KPI Analysis','Bonus & Compensation','Operations','Availability','Churn Analysis','Vendor Details','Live / Churn Map'];
function money(n){return n==null?'—':new Intl.NumberFormat('en-US',{maximumFractionDigits:0}).format(n)} function pct(n){return n==null?'—':`${(n*100).toFixed(1)}%`}
function toast(x){$('#toast').textContent=x;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),3500)}
function nav(){const admin=me.role==='admin'; $('#nav').innerHTML=pages.concat(admin?['Admin']:[]).map((p,i)=>`<button data-page="${p}" class="navitem ${i===0?'active':''}">${p}</button>`).join('');document.querySelectorAll('.navitem').forEach(b=>b.onclick=()=>loadPage(b.dataset.page));}
async function init(){me=(await api('/auth/me')).user; $('#userRole').textContent=me.role.toUpperCase();$('#userName').textContent=me.name||me.email; if(me.role!=='agent'){$('#refreshBtn').classList.remove('hidden');$('#refreshBtn').onclick=refresh;} $('#logoutBtn').onclick=async()=>{await api('/auth/logout',{method:'POST'});location.href='login.html'};$('#changePwd').onclick=()=>location.href='change-password.html';nav();await loadFilters();await loadPage('Overview');}
async function loadFilters(){const q=me.role==='agent'?`?agent=${encodeURIComponent(me.assignedAgent||'')}`:'';const d=await api('/dashboard/filters'+q); for(const [id,arr] of [['city',d.cities],['provider',d.providers],['agent',d.agents],['status',d.statuses]]){const el=$('#'+id);el.innerHTML='<option value="">All '+id+'s</option>'+arr.map(x=>`<option>${esc(x)}</option>`).join(''); if(me.role==='agent'&&id==='agent')el.value=me.assignedAgent||'';} $('#applyFilters').onclick=()=>{filters={};['city','provider','agent','status'].forEach(id=>{if($('#'+id).value)filters[id]=$('#'+id).value});loadPage($('#pageTitle').textContent);};}
function qs(){const s=new URLSearchParams(filters);return s.toString()?`?${s}`:''} function esc(x){return String(x??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
async function loadPage(page){$('#pageTitle').textContent=page;document.querySelectorAll('.navitem').forEach(b=>b.classList.toggle('active',b.dataset.page===page));if(page==='Live / Churn Map')return renderMap();if(page==='Admin')return renderAdmin();const d=await api('/dashboard/overview'+qs());$('#lastUpdated').textContent='Last update '+(d.lastUpdated?new Date(d.lastUpdated).toLocaleString():'—');renderDashboard(page,d);}
function card(title,value,sub=''){return `<div class="card"><div class="card-title">${title}</div><div class="card-value">${value}</div><div class="card-sub">${sub}</div></div>`}
function renderDashboard(page,d){const k=d.kpis||{};let html=`<div class="hero"><div><div class="eyebrow">${page}</div><h2>${d.vendorCount.toLocaleString()} vendors in current scope</h2></div><div class="health"><i></i> Data snapshot healthy</div></div><div class="cards">${card('Total vendors',d.vendorCount)}${card('NFC',pct(k.nfc),'source value')}${card('Cancel',pct(k.cancel))}${card('Return',pct(k.return))}${card('Refund',pct(k.refund))}${card('Availability',pct(k.availability))}${card('Hyper Delay',pct(k.hyperDelay))}${card('Assortment',k.assortment==null?'—':k.assortment.toFixed(0))}</div>`;
html+=`<div class="panel"><div class="panel-head"><h3>Vendor performance</h3><span>Server-side filtered</span></div><div class="tablewrap"><table><thead><tr><th>Vendor</th><th>Agent</th><th>City</th><th>Provider</th><th>Status</th><th>Availability</th><th>Cancel</th><th>Return</th></tr></thead><tbody>${d.vendors.slice(0,100).map(v=>`<tr><td>${esc(v.vendorName)}</td><td>${esc(v.agent)}</td><td>${esc(v.city)}</td><td>${esc(v.provider)}</td><td><span class="pill">${esc(v.status)}</span></td><td>${pct(v.availabilityPct)}</td><td>${pct(v.cancelledPct)}</td><td>${pct(v.returnedPct)}</td></tr>`).join('')}</tbody></table></div></div>`; if(page==='Agent Performance')html=agentView(d); if(page==='Vendor Performance')html=vendorView(d); if(page==='KPI Analysis')html=kpiView(d); if(page==='Bonus & Compensation')html=bonusView(d); if(page==='Churn Analysis')html=churnView(d); if(page==='Availability')html=availabilityView(d); if(page==='Operations')html=opsView(d); if(page==='Vendor Details')html=vendorView(d); $('#content').innerHTML=html;}
function agentView(d){const m={};d.vendors.forEach(v=>{if(!m[v.agent])m[v.agent]={n:0,a:0,c:0};m[v.agent].n++;if(v.availabilityPct!=null)m[v.agent].a+=v.availabilityPct;if(v.cancelledPct!=null)m[v.agent].c+=v.cancelledPct});return `<div class="cards">${Object.entries(m).sort((a,b)=>b[1].n-a[1].n).map(([a,x])=>card(a,x.n+' vendors',`Avg availability ${x.a?((x.a/x.n)*100).toFixed(1):'—'}%`)).join('')}</div>`}
function vendorView(d){return `<div class="cards">${d.vendors.slice(0,30).map(v=>card(v.vendorName||v.vendorId,v.agent||'Unassigned',`${v.city||'—'} · ${v.provider||'—'}`)).join('')}</div>`}
function kpiView(d){const k=d.kpis;return `<div class="cards">${card('NFC',pct(k.nfc),'Target must be configured in Admin')}${card('Cancel',pct(k.cancel))}${card('Return',pct(k.return))}${card('Refund',pct(k.refund))}${card('Hyper Delay',pct(k.hyperDelay))}${card('Availability',pct(k.availability))}</div><div class="notice">Bonus values are calculated server-side only after the corresponding target/configuration exists. Missing source fields are never guessed.</div>`}
function bonusView(d){return `<div class="panel"><div class="panel-head"><h3>Bonus & Compensation</h3></div><div class="notice">The bonus engine is active, but target configuration and some source fields must be present before a financial amount can be published. Use Admin → KPI Configuration.</div></div>`}
function churnView(d){const live=d.vendors.filter(v=>String(v.status||'').toLowerCase().includes('فعال')||String(v.status||'').toLowerCase().includes('live')).length;const churn=d.vendors.filter(v=>String(v.status||'').toLowerCase().includes('churn')).length;return `<div class="cards">${card('Live markets',live)}${card('Churn-labelled markets',churn)}${card('Reporting window','17 → 16','Selected month') }</div><div class="notice">Churn is calculated by the backend using the 17th-of-previous-month through 16th-of-selected-month window.</div>`}
function availabilityView(d){return `<div class="cards">${card('Average availability',pct(d.kpis.availability))}${card('Supermarket threshold','93%')}${card('Other Service threshold','90%')}</div>`}
function opsView(d){return `<div class="cards">${card('Gross orders',money(d.vendors.reduce((s,v)=>s+(v.grossOrder||0),0)))}${card('Delivered orders',money(d.vendors.reduce((s,v)=>s+(v.deliveredOrders||0),0)))}${card('Assortment',d.kpis.assortment==null?'—':d.kpis.assortment.toFixed(0))}</div>`}
async function renderMap(){const d=await api('/dashboard/map'+qs());$('#content').innerHTML=`<div class="panel map-panel"><div class="map-legend"><span>🟢 Live</span><span>🔴 Churn</span><span>${d.markers.length} mapped markets</span></div><div id="map"></div></div>`;const map=L.map('map').setView([35.72,51.39],10);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap'}).addTo(map);d.markers.forEach(v=>{const churn=String(v.status||'').toLowerCase().includes('churn');L.circleMarker([v.lat,v.lng],{radius:7,color:churn?'#d81f2a':'#1a9c5b',fillOpacity:.85}).addTo(map).bindPopup(`<b>${esc(v.name)}</b><br>Agent: ${esc(v.agent)}<br>City: ${esc(v.city)}<br>Provider: ${esc(v.provider)}<br>Status: ${esc(v.status)}<br>Live: ${esc(v.liveDate||'—')}<br>Churn: ${esc(v.churnDate||'—')}`)});}
async function renderAdmin(){if(me.role!=='admin')return $('#content').innerHTML='<div class="notice">Admin access required.</div>';const [u,k]=await Promise.all([api('/admin/users'),api('/admin/kpi-config')]);$('#content').innerHTML=`<div class="grid2"><div class="panel"><div class="panel-head"><h3>User management</h3><button class="primary" id="addUser">Add user</button></div><div class="tablewrap"><table><thead><tr><th>Email</th><th>Role</th><th>Agent</th><th>Status</th></tr></thead><tbody>${u.users.map(x=>`<tr><td>${esc(x.email)}</td><td>${x.role}</td><td>${esc(x.assigned_agent||'—')}</td><td>${x.status}</td></tr>`).join('')}</tbody></table></div></div><div class="panel"><div class="panel-head"><h3>KPI configuration</h3></div><div class="tablewrap"><table><thead><tr><th>Scope</th><th>KPI</th><th>Target</th><th>Bonus</th></tr></thead><tbody>${k.config.map(x=>`<tr><td>${x.city} / ${x.provider}</td><td>${x.kpi}</td><td>${x.target??'—'}</td><td>${money(x.bonus_amount)}</td></tr>`).join('')}</tbody></table></div></div></div>`;$('#addUser').onclick=async()=>{const email=prompt('Corporate email');if(!email)return;const role=prompt('Role: admin / manager / agent','agent');const assigned=role==='agent'?prompt('Assigned Agent identity'):null;try{const r=await api('/admin/users',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({email,role,assignedAgent:assigned})});alert('Initial password: '+r.initialPassword);renderAdmin();}catch(e){toast(e.message)}}}
async function refresh(){try{const r=await api('/admin/refresh',{method:'POST'});toast(`Refresh completed: ${r.vendorCount||0} vendors`);await loadFilters();await loadPage($('#pageTitle').textContent);}catch(e){toast(e.message)}}
init().catch(e=>toast(e.message));
